// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7wADXv36RnqR0w5q_E4fLtpGiKIg8ffc',
    appId: '1:388561553386:android:8a8307155e7264e9201493',
    messagingSenderId: '388561553386',
    projectId: 'gravity-9e634',
    storageBucket: 'gravity-9e634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1SmIJRzpcFVpd2KEPKLvKJzaGJAgGO9s',
    appId: '1:388561553386:ios:b16a031a4fadff9a201493',
    messagingSenderId: '388561553386',
    projectId: 'gravity-9e634',
    storageBucket: 'gravity-9e634.appspot.com',
    androidClientId: '388561553386-35c0pjsa6eboertpr2d5lbkdi9mkrgtb.apps.googleusercontent.com',
    iosClientId: '388561553386-79hrd4dvdei4uis44jme15o8vu3if5er.apps.googleusercontent.com',
    iosBundleId: 'com.intersubjective.gravity',
  );
}
